### ISSUE TITLE
[panic] thread 'main' panicked at src/localize.rs:20:10: Error while loading fallback language:

### ISSUE THREAD

**Issue by wiiznokes** [pop-os/cosmic-workspaces-epoch#92]
Really weird error. I'm using Fedora
```
> cosmic-workspaces 
thread 'main' panicked at src/localize.rs:20:10:
Error while loading fallback language: LanguageNotAvailable("en/cosmic_workspaces.ftl", LanguageIdentifier { language: Language(Some("en")), script: None, region: None, variants: None })
stack backtrace:
   0: rust_begin_unwind
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/std/src/panicking.rs:652:5
   1: core::panicking::panic_fmt
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1654:5
   3: core::result::Result<T,E>::expect
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/result.rs:1034:23
   4: cosmic_workspaces::localize::LANGUAGE_LOADER::{{closure}}
             at ./Documents/cosmic-workspaces-epoch/src/localize.rs:18:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
   7: once_cell::sync::Lazy<T,F>::force::{{closure}}
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/lib.rs:1310:28
   8: once_cell::sync::OnceCell<T>::get_or_init::{{closure}}
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/lib.rs:1120:57
   9: once_cell::imp::OnceCell<T>::initialize::{{closure}}
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/imp_std.rs:72:23
  10: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:294:13
  11: once_cell::imp::initialize_or_wait
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/imp_std.rs:196:20
  12: once_cell::imp::OnceCell<T>::initialize
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/imp_std.rs:68:9
  13: once_cell::sync::OnceCell<T>::get_or_try_init
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/lib.rs:1161:13
  14: once_cell::sync::OnceCell<T>::get_or_init
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/lib.rs:1120:19
  15: once_cell::sync::Lazy<T,F>::force
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/lib.rs:1309:13
  16: <once_cell::sync::Lazy<T,F> as core::ops::deref::Deref>::deref
             at ./.cargo/registry/src/index.crates.io-6f17d22bba15001f/once_cell-1.19.0/src/lib.rs:1376:13
  17: cosmic_workspaces::localize::localizer
             at ./Documents/cosmic-workspaces-epoch/src/localize.rs:39:38
  18: cosmic_workspaces::init_localizer
             at ./Documents/cosmic-workspaces-epoch/src/main.rs:718:21
  19: cosmic_workspaces::main
             at ./Documents/cosmic-workspaces-epoch/src/main.rs:749:5
  20: core::ops::function::FnOnce::call_once
             at /rustc/129f3b9964af4d4a709d1383930ade12dfe7c081/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by wiiznokes** [comment]
I had a version installed in `/usr/local/bin/`
